name: Upgrade PKHeX DLLs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout PKHeX Plugins
        run: |
          git clone -q --depth=5 --branch=cherrytree https://github.com/santacrab2/PKHeX-Plugins.git ${{ github.workspace }}/PKHeX-Plugins


      - name: Checkout PKHeX
        run: |
          git clone -q --depth=5 --branch=master https://github.com/kwsch/PKHeX.git ${{ github.workspace }}/PKHeX

      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Install NuGet
        run: |
          nuget update -self
          nuget install nuget.commandline -OutputDirectory .nuget -ExcludeVersion
          echo "$(pwd)/.nuget/nuget.commandline/tools" >> $GITHUB_PATH

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Restore NuGet dependencies for PKHeX-Plugins
        run: nuget restore ${{ github.workspace }}/PKHeX-Plugins/PKHeX-Plugins.sln

      - name: Restore NuGet dependencies for PKHeX
        run: nuget restore ${{ github.workspace }}/PKHeX/PKHeX.sln -NoCache

      - name: Build PKHeX.Core
        run: |
          msbuild ${{ github.workspace }}/PKHeX/PKHeX.Core/PKHeX.Core.csproj /p:Configuration=Release /p:Platform="Any CPU"

      - name: Copy PKHeX.Core.dll to NuGet cache
        shell: powershell
        run: |
          $nugetver = (Get-ChildItem "$env:UserProfile/.nuget/packages/pkhex.core" | Sort-Object -Property LastWriteTime -Descending)[0].Name
          Copy-Item "${{ github.workspace }}/PKHeX/PKHeX.Core/bin/Any CPU/Release/net10.0/PKHeX.Core.dll" "$env:UserProfile/.nuget/packages/pkhex.core/$nugetver/lib/net10.0"

      - name: Build PKHeX.Core.AutoMod
        run: |
          msbuild ${{ github.workspace }}/PKHeX-Plugins/PKHeX.Core.AutoMod/PKHeX.Core.AutoMod.csproj /p:Configuration=Release /p:Platform="Any CPU"

      - name: Prepare dlls
        run: |
          xcopy "${{ github.workspace }}\PKHeX-Plugins\PKHeX.Core.AutoMod\bin\Any CPU\Release\net10.0\PKHeX.Core.AutoMod.dll" ${{ github.workspace }}\GpssConsole\deps /Y
          xcopy "${{ github.workspace }}\PKHeX\PKHeX.Core\bin\Any CPU\Release\net10.0\PKHeX.Core.dll" ${{ github.workspace }}\GpssConsole\deps /Y

      - name: Remove other repo directories
        run: |
          # Remove PKHeX-Plugins directory
          Remove-Item -Recurse -Force ${{ github.workspace }}/PKHeX-Plugins
          # Remove PKHeX directory
          Remove-Item -Recurse -Force ${{ github.workspace }}/PKHeX

      - name: Restore NuGet dependencies for GpssConsole
        run: nuget restore ${{ github.workspace }}/GpssConsole/GpssConsole.sln -NoCache
        
      - name: Build GpssConsole.csproj
        run: |
          msbuild ${{ github.workspace }}/GpssConsole/GpssConsole.csproj /p:Configuration=Release /p:Platform="Any CPU"
        continue-on-error: true
        id: GpssConsole-build
        
      # If the build was successful, we're good to commit the new DLLs.
      - name: Commit and Push DLLs
        if: steps.GpssConsole-build.outcome == 'success'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add GpssConsole/deps/PKHeX.Core.dll GpssConsole/deps/PKHeX.Core.AutoMod.dll
          git commit -m "Update PKHeX.Core.dll and PKHeX.Core.AutoMod.dll"
          git push origin ${{ github.event.repository.default_branch }}
